### ISSUE TITLE
URL to `@kogs` scope in README.md cannot be viewed

### ISSUE THREAD

**Issue by sounisi5011** [Kruithne/kogs-argv#1]
Currently, the following URL is anchored to the page for viewing the `@kogs` collection: https://www.npmjs.com/settings/kogs/packages

https://github.com/Kruithne/kogs-argv/blob/6662e16aed4c3ec048dff82b4489a1fd0cce3b0b/README.md?plain=1#L260

However, this URL cannot be visible to other users.

![](https://user-images.githubusercontent.com/6049678/224999288-5ac3aefe-0e76-4909-90ba-55170c5be333.png)

You need to use this URL instead: https://www.npmjs.com/org/kogs

**Comment by Kruithne** [comment]
Oops, thanks for pointing that out! I'll get this resolved in all related packages.
